-- MySQL Script generated by MySQL Workbench
-- Wed Nov 16 11:06:25 2022
-- Model: New Model    Version: 10
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema 
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema 
-- -----------------------------------------------------

CREATE DATABASE my_books;
USE my_books;


-- -----------------------------------------------------
-- Table pessoa
-- -----------------------------------------------------
CREATE TABLE pessoa (
  cpf INT NOT NULL,
  nome VARCHAR(45) NOT NULL,
  email VARCHAR(45) NOT NULL,
  nacionalidade VARCHAR(45) NOT NULL,
  sexo VARCHAR(9) NOT NULL,
  data_nascimento DATETIME NOT NULL,
  PRIMARY KEY (cpf)
  );

-- -----------------------------------------------------
-- Table livros
-- -----------------------------------------------------
CREATE TABLE livros (
  isbn INT NOT NULL,
  titulo VARCHAR(200) NOT NULL,
  autor VARCHAR(45) NOT NULL,
  tipo_obra VARCHAR(45) NOT NULL,
  editora VARCHAR(45) NOT NULL,
  PRIMARY KEY (isbn));


-- -----------------------------------------------------
-- Table table1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table livros_has_pessoa
-- -----------------------------------------------------
CREATE TABLE livros_has_pessoa (
  isbn INT NOT NULL,
  pessoa_cpf INT NOT NULL,
  status_leitura VARCHAR(45) NOT NULL,
  PRIMARY KEY (isbn, pessoa_cpf),
  CONSTRAINT fk_livros_has_pessoa_livros
    FOREIGN KEY (isbn)
    REFERENCES livros (isbn),
    FOREIGN KEY (pessoa_cpf)
    REFERENCES pessoa (cpf)
    );


-- -----------------------------------------------------
-- Table autor
-- -----------------------------------------------------
CREATE TABLE autor (
  codigo INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  email VARCHAR(100) NULL,
  nome VARCHAR(100) NULL
  );

-- -----------------------------------------------------
-- Table genero
-- -----------------------------------------------------
CREATE TABLE genero (
  idgenero INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  nome_genero VARCHAR(45) NULL
  );



-- -----------------------------------------------------
-- Table autor_has_livros
-- -----------------------------------------------------
CREATE TABLE autor_has_livros (
  autor_codigo INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  livros_isbn INT NOT NULL,
  CONSTRAINT fk_autor_has_livros_autor1
    FOREIGN KEY (autor_codigo)
    REFERENCES autor (codigo),
    FOREIGN KEY (livros_isbn)
    REFERENCES livros (isbn)
);



-- -----------------------------------------------------
-- Table livros_has_genero
-- -----------------------------------------------------
CREATE TABLE livros_has_genero (
  livros_isbn INT NOT NULL,
  genero_idgenero INT NOT NULL,
  PRIMARY KEY (livros_isbn, genero_idgenero),
  CONSTRAINT fk_livros_has_genero_livros1
    FOREIGN KEY (livros_isbn)
    REFERENCES livros (isbn),
  CONSTRAINT fk_livros_has_genero_genero1
    FOREIGN KEY (genero_idgenero)
    REFERENCES genero (idgenero)
);


-- -----------------------------------------------------
-- Table editora
-- -----------------------------------------------------
CREATE TABLE editora (
  codigo_editora INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  nome_editora VARCHAR(45) NULL
  );


-- -----------------------------------------------------
-- Table livros_has_editora
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS livros_has_editora (
  livros_isbn INT NOT NULL,
  editora_codigo_editora INT NOT NULL,
  PRIMARY KEY (livros_isbn, editora_codigo_editora),
  CONSTRAINT fk_livros_has_editora_livros1
    FOREIGN KEY (livros_isbn)
    REFERENCES livros (isbn),
  CONSTRAINT fk_livros_has_editora_editora1
    FOREIGN KEY (editora_codigo_editora)
    REFERENCES editora (codigo_editora)
  );

-- ------------------------------------------------------
-- ATIVIDADES PEDIDAS 
-- ------------------------------------------------------

INSERT INTO pessoa (
  cpf,
  nome, 
  email,
  nacionalidade,
  sexo,
  data_nascimento
)

VALUES (80222,'Carlos Duarte', 'carlosduarte@gmail.com','Brasil','Masculino','1982-02-02'),
	   (37406,'Pedro Ricardo Alves','pedroalvess@gmail.com', 'Brasil', 'Masculino','1991-04-24'),
	   (96352,'Pietra Silva','pietraa123@gmailcom', 'Brasil','Feminino','2000-11-25'),
	   (07868,'Nicole Freutas','freitasnicole@gmail.com','Portugal','Feminino','2000-02-23'),
	   (30025,'Lucas Elias Novaes','lucasnovaes@gmail.com','França','Masculino','1998-03-13'),
	   (80008,'Augusto Almeida','augusto89@gmail.com','Brasil','Masculino','1989-04-21'),
	   (58639,'Claudio Corte Real','reiclaudio2gmail.com','Inglaterra','Masculino','1998-06-25'),
	   (46683,'Fernanda Caldeira','fernandinha@gmail.com','Brasil','Feminino','2003-05-25'),
       (76899,'Kamily Freitas','kamilyfreitas@gmail.com','Argentina','Feminino','1997-01-07'),
       (20395,'Stefany Calina','stefanyameriacan@gmail.com','Estados Unidos','Feminino','2004-08-10');

INSERT INTO livros (
	isbn,
    titulo,
    autor,
    tipo_obra,
    editora
)

VALUES (156987,'Minha Vida Fora de Série','Paula Pimenta','Romance Infantojuvenil','Gutenberg'),
	   (655987,'Feminismo: Perversão e Subversão','Ana Caroline Camapgnolo','Política','Vide Editorial'),
       (963254,'Enquanto Isso','Fernanda Witwytzky','Cristão','Thomas Nelson'),
       (856932,'O Cristão e a Política','Nikolas Ferreira','Cristão','Central Gospel'),
       (235478,'Jogos Vozares','Suzanne Collins','Distopia','Rocco'),
       (123654,'Harry Potter e a Pedra Filosofal','J.K. Rowling','Fantasia','Rocco'),
       (236548,'Para Todos os Garotos que Já Amei','Jenny Han','Romance','Intrínsica'),
       (546987,'Corte de Espinhos e Rosas','Sarah J. Mass','Fantasia','Galera Record'),
       (789565,'O duque e eu','Julia Quinn','Romance de época','Editora Arqueiro'),
       (266544,'A Revolução do bichos','George Orwell','Política','Principis');

INSERT INTO autor (
    email,
    nome
)
VALUES ('paulapimentaescritora@gmail.com','Paula Pimenta'),
       ('anacarolinecampagnolo@gmail.com','Ana Caroline Campagnolo'),
       ('witwytzky.fernanda@gmail.com','Fernanda Witwytzky'),
       ('nikolasferreira@hotmail.com','Nikolas Ferreira'),
       ('suzannecollins@outblook.com','Suzanne Collins'),
       ('jkrowliing@hotmail.com','J.K. Rowling'),
       ('hanjenny@hotmail.com','Jenny Han'),
       ('sarahjmass@gmail.com','Saraj J. Mass'),
       ('quinnjulia@outblook.com','Julia Quinn'),
       ('georgeorwell@gmail.com','Geogre Orwell');

INSERT INTO genero (
   nome_genero
)
  
VALUES ('Romance'),
       ('Fantasia'),
       ('Política'),
       ('Cristão'),
       ('Romance de época'),
       ('Infantojuvenil'),
       ('Distopia'),
       ('Não-ficção'),
       ('Clássico'),
       ('Autoajuda');

INSERT INTO editora (
  nome_editora
)

VALUES ('Gutenberg'),
       ('Vide Editora'),
       ('Thomas Nelson'),
       ('Central Gospel'),
       ('Rocco'),
       ('Intrínseca'),
       ('Galera Record'),
       ('Editora Arqueiro'),
       ('Princípis'),
       ('Editora Seguinte');

UPDATE pessoa SET nome = 'Carlinhos Maia' WHERE cpf = 8022;
UPDATE pessoa SET nome ='Sofia Nascimento' WHERE cpf = 46683;
UPDATE pessoa SET nome ='Amanda da Silva' WHERE cpf = 20395;
UPDATE pessoa SET nome ='João Augusto' WHERE cpf = 30025;
UPDATE pessoa SET nome ='Noah Urrea'WHERE cpf = 15863;

UPDATE livros SET titulo = 'Fazendo Meu Filme' WHERE isbn = 156987;
UPDATE livros SET titulo ='Guia de Bolso Contra Mentiras Feministas' WHERE isbn = 655987;
UPDATE livros SET titulo ='As Primeiras Quatro Estações' WHERE isbn = 963254;
UPDATE livros SET titulo ='Em Chamas' WHERE isbn = 236548;
UPDATE livros SET titulo ='Corte de Névoa e Fúria'WHERE isbn = 546987;

UPDATE autor SET email = 'pimentapaula@hotmail' WHERE codigo = 1;
UPDATE autor SET email ='anacampagnolo@alesc.com.br' WHERE codigo = 5;
UPDATE autor SET email ='ferreiranikolas@brasil.com.br' WHERE codigo = 8;
UPDATE autor SET email ='jennyhan@gmail.com' WHERE codigo = 4;
UPDATE autor SET email ='sarahjmass@outblook'WHERE codigo = 10;

UPDATE genero SET nome_genero = 'Distopia' WHERE idgenero = 4;
UPDATE genero SET nome_genero ='Romance' WHERE idgenero = 9;
UPDATE genero SET nome_genero ='Fantasia' WHERE idgenero = 3;
UPDATE genero SET nome_genero ='Cristão' WHERE idgenero = 6;
UPDATE genero SET nome_genero ='Política'WHERE idgenero = 10;

UPDATE editora SET nome_editora = 'Editora Seguinte' WHERE codigo_editora = 1;
UPDATE editora SET nome_editora ='Princípis' WHERE codigo_editora = 5;
UPDATE editora SET nome_editora ='Thomas Nelson' WHERE codigo_editora = 9;
UPDATE editora SET nome_editora ='Galera Record' WHERE codigo_editora = 3;
UPDATE editora SET nome_editora ='Rocco'WHERE codigo_editora = 7;

DELETE FROM pessoa WHERE cpf = 30025;
DELETE FROM pessoa WHERE cpf = 76899;
DELETE FROM pessoa WHERE cpf = 20395;
DELETE FROM pessoa WHERE cpf = 96352;
DELETE FROM pessoa WHERE cpf = 46683;

DELETE FROM livros WHERE isbn = 156987;
DELETE FROM livros WHERE isbn = 123654;
DELETE FROM livros WHERE isbn = 266544;
DELETE FROM livros WHERE isbn = 546987;
DELETE FROM livros WHERE isbn = 236548;

DELETE FROM autor WHERE codigo = 4;
DELETE FROM autor WHERE codigo = 8;
DELETE FROM autor WHERE codigo = 7;
DELETE FROM autor WHERE codigo = 3;
DELETE FROM autor WHERE codigo = 5;

DELETE FROM genero WHERE idgenero = 1;
DELETE FROM genero WHERE idgenero = 5;
DELETE FROM genero WHERE idgenero = 6;
DELETE FROM genero WHERE idgenero = 2;
DELETE FROM genero WHERE idgenero = 10;

DELETE FROM editora WHERE codigo_editora = 1;
DELETE FROM editora WHERE codigo_editora = 2;
DELETE FROM editora WHERE codigo_editora = 6;
DELETE FROM editora WHERE codigo_editora = 7;
DELETE FROM editora WHERE codigo_editora = 9;

SELECT * FROM pessoa ORDER BY cpf;

SELECT * FROM livros ORDER BY isbn;

SELECT * FROM autor ORDER BY codigo;

SELECT * FROM genero ORDER BY idgenero;

SELECT * FROM editora ORDER BY codigo_editora;


SELECT * FROM pessoa WHERE cpf = 20395;

SELECT * FROM livros WHERE isbn = 963254;

SELECT * FROM autor WHERE codigo = 5;

SELECT * FROM genero WHERE idgenero = 3;

SELECT * FROM editora WHERE codigo_editora = 8;

SELECT pessoa.cpf, livros.isbn FROM pessoa RIGHT JOIN livros ON pessoa.cpf = livros.isbn;

SELECT livros.isbn, autor.codigo FROM livros INNER JOIN autor ON livros.isbn = autor.codigo;

SELECT autor.codigo, editora.codigo_editora FROM autor LEFT JOIN editora ON autor.codigo = editora.codigo_editora;

SELECT editora.codigo_editora, genero.idgenero FROM editora INNER JOIN genero ON editora.codigo_editora = genero.idgenero;

SELECT genero.idgenero, autor.codigo FROM genero INNER JOIN autor ON genero.idgenero = autor.codigo;

-- DROP DATABASE my_books;