-- MySQL Script generated by MySQL Workbench
-- Wed Nov 16 11:06:25 2022
-- Model: New Model    Version: 10
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema 
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema 
-- -----------------------------------------------------
CREATE DATABASE meus_livros ;
USE meus_livros;
-- -----------------------------------------------------
-- Table pessoa
-- -----------------------------------------------------
CREATE TABLE pessoa (
  cpf INT NOT NULL,
  nome VARCHAR(45) NOT NULL,
  email VARCHAR(45) NOT NULL,
  nacionalidade VARCHAR(45) NOT NULL,
  sexo VARCHAR(8) NOT NULL,
  data_nascimento INT NOT NULL,
  PRIMARY KEY (cpf)
  );

-- -----------------------------------------------------
-- Table livros
-- -----------------------------------------------------
CREATE TABLE livros (
  isbn INT NOT NULL,
  titulo VARCHAR(200) NOT NULL,
  autor VARCHAR(45) NOT NULL,
  tipo_obra VARCHAR(45) NOT NULL,
  editora VARCHAR(45) NOT NULL,
  PRIMARY KEY (isbn));


-- -----------------------------------------------------
-- Table table1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table livros_has_pessoa
-- -----------------------------------------------------
CREATE TABLE livros_has_pessoa (
  isbn INT NOT NULL,
  pessoa_cpf INT NOT NULL,
  status_leitura VARCHAR(45) NOT NULL,
  PRIMARY KEY (isbn, pessoa_cpf),
  CONSTRAINT fk_livros_has_pessoa_livros
    FOREIGN KEY (isbn)
    REFERENCES livros (isbn)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_livros_has_pessoa_pessoa1
    FOREIGN KEY (pessoa_cpf)
    REFERENCES pessoa (cpf)
    );


-- -----------------------------------------------------
-- Table autor
-- -----------------------------------------------------
CREATE TABLE autor (
  codigo INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  email VARCHAR(45) NULL,
  nome VARCHAR(45) NULL,
  PRIMARY KEY (codigo))

-- -----------------------------------------------------
-- Table genero
-- -----------------------------------------------------
CREATE TABLE genero (
  idgenero INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  nome_genero VARCHAR(45) NULL,
  PRIMARY KEY (idgenero)
  );



-- -----------------------------------------------------
-- Table autor_has_livros
-- -----------------------------------------------------
CREATE TABLE autor_has_livros (
  autor_codigo INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  livros_isbn INT NOT NULL,
  PRIMARY KEY (autor_codigo, livros_isbn),
  CONSTRAINT fk_autor_has_livros_autor1
    FOREIGN KEY (autor_codigo)
    REFERENCES autor (codigo),
    FOREIGN KEY (livros_isbn)
    REFERENCES livros (isbn)
);



-- -----------------------------------------------------
-- Table livros_has_genero
-- -----------------------------------------------------
CREATE TABLE livros_has_genero (
  livros_isbn INT NOT NULL,
  genero_idgenero INT NOT NULL,
  PRIMARY KEY (livros_isbn, genero_idgenero),
  CONSTRAINT fk_livros_has_genero_livros1
    FOREIGN KEY (livros_isbn)
    REFERENCES livros (isbn),
  CONSTRAINT fk_livros_has_genero_genero1
    FOREIGN KEY (genero_idgenero)
    REFERENCES genero (idgenero)
);


-- -----------------------------------------------------
-- Table editora
-- -----------------------------------------------------
CREATE TABLE editora (
  codigo_editora INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  nome_editora VARCHAR(45) NULL,
  PRIMARY KEY (codigo_editora)
  );


-- -----------------------------------------------------
-- Table livros_has_editora
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS livros_has_editora (
  livros_isbn INT NOT NULL,
  editora_codigo_editora INT NOT NULL,
  PRIMARY KEY (livros_isbn, editora_codigo_editora),
  CONSTRAINT fk_livros_has_editora_livros1
    FOREIGN KEY (livros_isbn)
    REFERENCES livros (isbn),
  CONSTRAINT fk_livros_has_editora_editora1
    FOREIGN KEY (editora_codigo_editora)
    REFERENCES editora (codigo_editora)
  );

-- ------------------------------------------------------
-- ATIVIDADES PEDIDAS 
-- ------------------------------------------------------

INSERT INTO pessoa (
  cpf,
  nome, 
  email,
  nacionalidade,
  sexo,
  data_nascimento
)

VALUES (80222520884,'Carlos Duarte', 'carlosduarte@gmailcom','Brasil','Masculino','02-02-1982'),
	   (37406414285,'Pedro Ricardo Alves','pedroalvess@gmailcom', 'Brasil', 'Masculino','04-24-1991'),
	   (96352539076,'Pietra Silva','pietraa123@gmailcom', 'Brasil','França','Feminino','11-03-2000'),
	   (07868915722,'Nicole Freutas','freitasnicole@gmailcom','Portugal','Feminino','02-23-2000'),
	   (30025017942,'Lucas Elias Novaes','lucasnovaes@gmail.com','França','Masculino','03-13-1998'),
	   (80008486352,'Augusto Almeida','augusto89@gmail.com','Brasil','Masculino','04-21-1989'),
	   (58639241449,'Claudio Corte Real','reiclaudio2gmail.com','Inglaterra','Masculino','06-25-1998'),
	   (46683941220,'Fernanda Caldeira','fernandinha@gmail.com','Brasil','Feminino','05-25-2003'),
     (76899799120,'Kamily Freitas','kamilyfreitas@gmail.com','Argentina','Feminino','01-07-1997'),
     (20395268117,'Stefany Calina','stefanyameriacan@gmail.com','Estados Unidos','Feminino','08-10-2004');

INSERT INTO livros (
	isbn,
    titulo,
    autor,
    tipo_obra,
    editora
)

VALUES (1569874326987,'Minha Vida Fora de Série','Paula Pimenta','Romance Infantojuvenil','Gutenberg'),
	     (6559874632158,'Feminismo: Perversão e Subversão','Ana Caroline Camapgnolo','Política','Vide Editorial'),
       (9632547813654,'Enquanto Isso','Fernanda Witwytzky','Cristão','Thomas Nelson'),
       (8569321456987,'O Cristão e a Política','Nikolas Ferreira','Cristão','Central Gospel')
       (2365489517585,'Jogos Vozares','Suzanne Collins','Distopia','Rocco'),
       (1236548974121,'Harry Potter e a Pedra Filosofal','J.K. Rowling','Fantasia','Rocco'),
       (2365489741236,'Para Todos os Garotos que Já Amei','Jenny Han','Romance','Intrínsica'),
       (5469874223611,'Corte de Espinhos e Rosas','Sarah J. Mass','Fantasia','Galera Record'),
       (7895654621852,'O duque e eu','Julia Quinn','Romance de época','Editora Arqueiro'),
       (2665448947132,'A Revolução do bichos','George Orwell','Política','Principis');

INSERT INTO autor (
    codigo,
    email,
    nome
)

VALUES ('paulapimentaescritora@gmail.com','Paula Pimenta'),
       ('anacarolinecampagnolo@gmail.com','Ana Caroline Campagnolo'),
       ('witwytzky.fernanda@gmail.com','Fernanda Witwytzky'),
       ('nikolasferreira@hotmail.com','Nikolas Ferreira'),
       ('suzannecollins@outblook.com','Suzanne Collins'),
       ('jkrowliing@hotmail.com','J.K. Rowling'),
       ('hanjenny@hotmail.com','Jenny Han'),
       ('sarahjmass@gmail.com','Saraj J. Mass'),
       ('quinnjulia@outblook.com','Julia Quinn'),
       ('georgeorwell@gmail.com','Geogre Orwell');

INSERT INTO genero (
    idgenero,
   nome_genero
)
  
VALUES ('Romance'),
       ('Fantasia'),
       ('Política'),
       ('Cristão'),
       ('Romance de época'),
       ('Infantojuvenil'),
       ('Distopia'),
       ('Não-ficção'),
       ('Clássico'),
       ('Autoajuda');

INSERT INTO editora (
  codigo_editora,
  nome_editora
)

VALUES ('Gutenberg'),
       ('Vide Editora'),
       ('Thomas Nelson'),
       ('Central Gospel'),
       ('Rocco'),
       ('Intrínseca'),
       ('Galera Record'),
       ('Editora Arqueiro'),
       ('Princípis')
       ('Editora Seguinte');

UPDATE pessoa SET nome = 'Carlinhos Maia' WHERE cpf = 80222520884;
UPDATE pessoa SET nome ='Sofia Nascimento' WHERE cpf = 46683941220;
UPDATE pessoa SET nome ='Amanda da Silva' WHERE cpf = 20395268117;
UPDATE pessoa SET nome ='João Augusto' WHERE cpf = 30025017942;
UPDATE pessoa SET nome ='Noah Urrea'WHERE cpf = 158639241449;

UPDATE livros SET titulo = 'Fazendo Meu Filme' WHERE isbn = 1569874326987;
UPDATE livros SET titulo ='Guia de Bolso Contra Mentiras Feministas' WHERE isbn = 6559874632158;
UPDATE livros SET titulo ='As Primeiras Quatro Estações' WHERE isbn = 9632547813654;
UPDATE livros SET titulo ='Em Chamas' WHERE isbn = 2365489517585;
UPDATE livros SET titulo ='Corte de Névoa e Fúria'WHERE isbn = 5469874223611;

UPDATE autor SET email = 'pimentapaula@hotmail' WHERE codigo = 1;
UPDATE autor SET email ='anacampagnolo@alesc.com.br' WHERE codigo = 5;
UPDATE autor SET email ='ferreiranikolas@brasil.com.br' WHERE codigo = 8;
UPDATE autor SET email ='jennyhan@gmail.com' WHERE codigo = 4;
UPDATE autor SET email ='sarahjmass@outblook'WHERE codigo = 10;

UPDATE genero SET nome_genero = 'Distopia' WHERE idgenero = 4;
UPDATE genero SET nome_genero ='Romance' WHERE idgenero = 9;
UPDATE genero SET nome_genero ='Fantasia' WHERE idgenero = 3;
UPDATE genero SET nome_genero ='Cristão' WHERE idgenero = 6;
UPDATE genero SET nome_genero ='Política'WHERE idgenero = 10;

UPDATE editora SET nome_editora = 'Editora Seguinte' WHERE codigo_editora = 1;
UPDATE editora SET nome_editora ='Princípis' WHERE codigo_editora = 5;
UPDATE editora SET nome_editora ='Thomas Nelson' WHERE codigo_editora = 9;
UPDATE editora SET nome_editora ='Galera Record' WHERE codigo_editora = 3;
UPDATE editora SET nome_editora ='Rocco'WHERE codigo_editora = 7;

DELETE FROM pessoa WHERE cpf = 30025017942;
DELETE FROM pessoa WHERE cpf = 76899799120;
DELETE FROM pessoa WHERE cpf = 20395268117;
DELETE FROM pessoa WHERE cpf = 96352539076;
DELETE FROM pessoa WHERE cpf = 46683941220;

DELETE FROM livros WHERE isbn = 1569874326987;
DELETE FROM livros WHERE isbn = 1236548974121;
DELETE FROM livros WHERE isbn = 2665448947132;
DELETE FROM livros WHERE isbn = 5469874223611;
DELETE FROM livros WHERE isbn = 2365489741236;

DELETE FROM autor WHERE codigo = 4;
DELETE FROM autor WHERE codigo = 8;
DELETE FROM autor WHERE codigo = 7;
DELETE FROM autor WHERE codigo = 3;
DELETE FROM autor WHERE codigo = 5;

DELETE FROM genero WHERE idgenero = 1;
DELETE FROM genero WHERE idgenero = 5;
DELETE FROM genero WHERE idgenero = 6;
DELETE FROM genero WHERE idgenero = 2;
DELETE FROM genero WHERE idgenero = 10;

DELETE FROM editora WHERE codigo_editora = 1;
DELETE FROM editora WHERE codigo_editora = 2;
DELETE FROM editora WHERE codigo_editora = 6;
DELETE FROM editora WHERE codigo_editora = 7;
DELETE FROM editora WHERE codigo_editora = 9;

SELECT * FROM pessoa ORDER BY cpf;

SELECT * FROM livros ORDER BY isbn;

SELECT * FROM autor ORDER BY codigo;

SELECT * FROM genero ORDER BY idgenero;

SELECT * FROM editora ORDER BY codigo_editora;



       
