-- MySQL Script generated by MySQL Workbench
-- Wed Nov 16 11:06:25 2022
-- Model: New Model    Version: 10
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema 
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema 
-- -----------------------------------------------------
CREATE DATABASE meus_livros ;
USE meus_livros;
-- -----------------------------------------------------
-- Table pessoa
-- -----------------------------------------------------
CREATE TABLE pessoa (
  cpf INT NOT NULL,
  nome VARCHAR(45) NOT NULL,
  email VARCHAR(45) NOT NULL,
  nacionalidade VARCHAR(45) NOT NULL,
  sexo VARCHAR(8) NOT NULL,
  data_nascimento INT NOT NULL,
  PRIMARY KEY (cpf)
  );

-- -----------------------------------------------------
-- Table livros
-- -----------------------------------------------------
CREATE TABLE livros (
  isbn INT NOT NULL,
  titulo VARCHAR(200) NOT NULL,
  autor VARCHAR(45) NOT NULL,
  tipo_obra VARCHAR(45) NOT NULL,
  PRIMARY KEY (isbn));


-- -----------------------------------------------------
-- Table table1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table livros_has_pessoa
-- -----------------------------------------------------
CREATE TABLE livros_has_pessoa (
  isbn INT NOT NULL,
  pessoa_cpf INT NOT NULL,
  status_leitura VARCHAR(45) NOT NULL,
  PRIMARY KEY (isbn, pessoa_cpf),
  CONSTRAINT fk_livros_has_pessoa_livros
    FOREIGN KEY (isbn)
    REFERENCES livros (isbn)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_livros_has_pessoa_pessoa1
    FOREIGN KEY (pessoa_cpf)
    REFERENCES pessoa (cpf)
    );


-- -----------------------------------------------------
-- Table autor
-- -----------------------------------------------------
CREATE TABLE autor (
  codigo INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  email VARCHAR(45) NULL,
  nome VARCHAR(45) NULL,
  PRIMARY KEY (codigo))

-- -----------------------------------------------------
-- Table genero
-- -----------------------------------------------------
CREATE TABLE genero (
  idgenero INT NOT NULL,
  nome_genero VARCHAR(45) NULL,
  PRIMARY KEY (idgenero)
  );



-- -----------------------------------------------------
-- Table autor_has_livros
-- -----------------------------------------------------
CREATE TABLE autor_has_livros (
  autor_codigo INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  livros_isbn INT NOT NULL,
  PRIMARY KEY (autor_codigo, livros_isbn),
  CONSTRAINT fk_autor_has_livros_autor1
    FOREIGN KEY (autor_codigo)
    REFERENCES autor (codigo),
    FOREIGN KEY (livros_isbn),
    REFERENCES livros (isbn)
);



-- -----------------------------------------------------
-- Table livros_has_genero
-- -----------------------------------------------------
CREATE TABLE livros_has_genero (
  livros_isbn INT NOT NULL,
  genero_idgenero INT NOT NULL,
  PRIMARY KEY (livros_isbn, genero_idgenero),
  CONSTRAINT fk_livros_has_genero_livros1
    FOREIGN KEY (livros_isbn)
    REFERENCES livros (isbn),
  CONSTRAINT fk_livros_has_genero_genero1
    FOREIGN KEY (genero_idgenero)
    REFERENCES genero (idgenero)
);


-- -----------------------------------------------------
-- Table editora
-- -----------------------------------------------------
CREATE TABLE editora (
  codigo_editora INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  nome_editora VARCHAR(45) NULL,
  PRIMARY KEY (codigo_editora)
  );


-- -----------------------------------------------------
-- Table livros_has_editora
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS livros_has_editora (
  livros_isbn INT NOT NULL,
  editora_codigo_editora INT NOT NULL,
  PRIMARY KEY (livros_isbn, editora_codigo_editora),
  CONSTRAINT fk_livros_has_editora_livros1
    FOREIGN KEY (livros_isbn)
    REFERENCES livros (isbn),
  CONSTRAINT fk_livros_has_editora_editora1
    FOREIGN KEY (editora_codigo_editora)
    REFERENCES editora (codigo_editora)
  );

-- ------------------------------------------------------
-- ATIVIDADES PEDIDAS 
-- ------------------------------------------------------

INSERT INTO (
  cpf,
  nome, 
  email,
  nacionalidade
  sexo,
  data_nascimento,
)

VALUES (80222520884,'Carlos Duarte', 'carlosduarte@gmailcom', 'Brasil','Masculino','02-02-1982')
       (37406414285,'Pedro Ricardo Alves','pedroalvess@gmailcom', 'Brasil', 'Masculino','04-24-1991')
       (96352539076,'Pietra Silva','pietraa123@gmailcom', 'Brasil','França','Feminino','11-03-2000')
       (07868915722,'Nicole Freutas','freitasnicole@gmailcom','Portugal')
